DELETE http://localhost:3001/api/persons/1

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{

    
}

###

GET http://localhost:3001/api/persons/60651addba9cafec59b157f