GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/6064ed7080de4ff14b215c77

###

DELETE http://localhost:3001/api/persons/60653b3b7a998a0c6e84b54

###

POST http://localhost:3001/api/persons/
content-type: application/json

{
  "name": "2f",
  "number": "234132"
}

###

PUT http://localhost:3001/api/persons/6064ed7080de4ff14b215c77
content-type: application/json

{
  "name": "Jonny the dog",
  "number": "12390293842234"
}